CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(160),
	email VARCHAR(160),
	username VARCHAR(160),
	password VARCHAR(160),
	token VARCHAR(160),
	phone VARCHAR(160),
	boiler BOOLEAN DEFAULT FALSE,
	role VARCHAR(160) DEFAULT 'USER',
	flat INT
)

CREATE TABLE user_ids (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id INT,
	ck VARCHAR(20),
	csb VARCHAR(20),
	cbb VARCHAR(20),
	hk VARCHAR(20),
	hsb VARCHAR(20),
	hbb VARCHAR(20),
	created_date BIGINT
)